type Poema = { 
    texto: string,
    align?: 'left' | 'right' | 'center'
}[][]

export const poema: Poema = [
    [
        { texto: 'Con abundante agua me quito los bostezos de la cara,' },
        { texto: 'saludo el día con un limpio pensamiento: ojalá ' },
        { texto: 'cada vez que musitara yo ' },
        { texto: '—con rabia, como mastican avena los culturistas— ' },
        { texto: 'dos o tres mecagoendioses, mis sílabas fueran un crucial y doloroso' },
        { texto: 'golpe de luz, ¡ojalá un golpe de luz!, vergüenza agarrada a un espejo. ' },
        { texto: 'mecagoendioses anagnórisis, nada queda para el poeta ' },
        { texto: 'salvo el mecagoendiós o si acaso tocar el piano. ' },
        { texto: '¡mueran la pudibundez y la melindre!' },
        { texto: 'os quiero tanto a todos pero pienso mataros ' },
        { texto: 'para corregir esta deriva, este exceso de civilización' },
    ],
    [
        { texto: "¡incívico quebrantahuesos que al cuadrúpedo derrengas!,"},
        { texto: "¿qué será desayunar la negrura de tus ojos hundidos?"},
        { texto: "¡pataplaf!", align: "right" },
        { texto: "excepcional carajillo mañanero, "},
        { texto: "peligroso y purificador, ay,"},
        { texto: "¡cívico castor que la presa construyes!, pronto desbordará la mierda "},
        { texto: "que ha de llevarnos a todos:"},
        { texto: "tu mamá te quiere y para ti ahorró muchas pesetas;"},
        { texto: "tu tía te quiere y para ti trajo un sobre con perras;"},
        { texto: "tu hermana está triste, no tiene nada que ofrecer,"},
        { texto: "la muy puta,"},
        { texto: "¿en qué lo habrá gastado?, mecagoendiós."},
        { texto: "os quiero tanto a todos pero pienso mataros "},
        { texto: "por haberme apartado de mi sueño: "},
        { texto: "ser Carlos Slim."}
    ],
    [
        { texto: "acompáñame ahora a la Iglesia, Cólera-del-Pelida," },
        { texto: "la que esforzadamente levantaron nuestros papás y nuestras mamás; " },
        { texto: "por sus pasillos hay siempre una fiesta" },
        { texto: "donde se celebra el consumo de oxígeno, " },
        { texto: "la correcta postura al sentarse," },
        { texto: "todo eso. la Iglesia provee a muchos" },
        { texto: "de incontables litros de condescendencia-del-tullido," },
        { texto: "te la van a echar" },
        { texto: "en el café" },
        { texto: "cuidadito." }
    ],
    [
        { texto: "mi mamá quiere que un párroco me enseñe el Trivio, el Cuadrivio" },
        { texto: "el Nosequé, el Sisemenos, así me lo ha hecho prometer." },
        { texto: "de camino a la Capilla está la gente, celebrando. " },
        { texto: "y aquel que no celebra atronadoramente no es más que un fantasma huesudo," },
        { texto: "mecagoendiós, y apenas se atreve a mirarme, ¡zorrito" },
        { texto: "al que llamo Cólera-del-Pelida! tú eres mi único amigo," },
        { texto: "la exuberancia tuya procedimental y onomástica;" },
        { texto: "tú, zorrito fabuloso," },
        { texto: "proporcionarás a los jóvenes satisfacción estética" },
        { texto: "y desafíos intelectuales" },
        { texto: "cuando yo ya no esté," },
        { texto: "«grf, grf»", align: 'right' },
        { texto: "pero el párroco en su Capilla" },
        { texto: "repite las palabras ¡tantas atropelladas veces!" },
        { texto: "son ya las frases camiones llenos de puercos, leves puercos y sucios" },
        { texto: "adelantándose unos a otros " },
        { texto: "—pero hemos prometido que vendríamos," },
        { texto: "Cólera-del-Pelida, a escucharlos a todos," },
        { texto: "todo eso que tienen que decir; después nos señalará el párroco" },
        { texto: "con su dedo de plástico*" },
        { texto: "y nosotros, modulando el caudal de nuestra prosa," },
        { texto: "nos sumaremos" },
        { texto: "a la moderación general" },
        { texto: "con un comentario compendioso, nada más que " },
        { texto: "«no sé qué texto me recuerda a no sé qué película»—," },
        { texto: "en seguida estaremos fuera, te lo prometo," },
        { texto: "los quiero tanto a todos pero pienso matarlos " },
        { texto: "como quien saca de su miseria a un roedor moribundo, envenenado," },
        { texto: "que no supo distinguir entre cereal y detergente." },
    ],
    [
        { texto: "salgo desayunado de mi feliz guarida" },
        { texto: "cuando alguien, al grito de " },
        { texto: "¡algo va!", align: "right" },
        { texto: "vacía sobre mí un cubo, " },
        { texto: "me empapa de la-condescendencia-del-tullido," },
        { texto: "y luego oigo con las orejitas: " },
        { texto: "«este es el resumen perfecto de tu estancia en la Tierra " },
        { texto: "desde que acudías religiosamente a tu centro de enseñanza primaria». " },
        { texto: "me lo dice un zorrito de fábula que por ahí apareció. " },
        { texto: "«te llamaré Cólera-del-Pelida», le digo." },
        { texto: "el zorrito entra al corral del hombre del cubo, " },
        { texto: "destripa sin miramientos a sus gallinas ponedoras," },
        { texto: "orina sobre su título de Bachillerato. " },
        { texto: "«Cólera-del-Pelida», le digo, " },
        { texto: "«no eres el fuego de los justos, pero buscas dignidad y gloria:" },
        { texto: "deseo con todo el pecho que la encuentres»," },
                                                    { texto: "«grf, grf», contesta él." },
        { texto: "aquí a la intemperie es donde suceden las cosas, " },
        { texto: "donde somos testigos," },
        { texto: "conocemos la extrema pureza de los momentos;" },
        { texto: "la paz no es gregaria ni tonta aquí" },
        { texto: "no se ha inventado la paz; en fin:" },
        { texto: "qué no ha de ser regalado a quien con esta disposición camina; mecagoendiós" },
        { texto: "os quiero mucho a todos pero pienso mataros " },
        { texto: "por haberme privado de una maldad sofisticada y cierta, " },
        { texto: "por haberme regalado en cambio una legión de lerdos y un zorro pequeño." },
    ],
    [
        { texto: "allí al final se ve la oscuridad del ocaso,"},
        { texto: "zorrito mío, ganándose la luz del entusiasmo nuestro."},
        { texto: "se acaba el túnel, y deyectados al mundo de nuevo "},
        { texto: "esquivamos los chorritos de condescendencia-del-tullido "},
        { texto: "y escupimos a la menor ocasión un poco de bilis, "},
        { texto: "¡casi se le van a uno las ganas de continuar!, "},
        { texto: "«grf, grf»,", align: 'right' },
        { texto: "parece todo una loca danza de cobras y roedores "},
        { texto: "que seguirá para siempre, "},
        { texto: "cuando yo me haya muerto "},
        { texto: "dejando sin respuesta poderosas cuestiones, "},
        { texto: "cuando las señoras heladas reivindiquen la compostura "},
        { texto: "levitando con ayuda de una soga, "},
        { texto: "seguirá cuando nos hayan golpeado a todos "},
        { texto: "al menos una vez —crujirán las caderas de nuestras madres"},
        { texto: "y quién sabe qué mandíbulas—, seguirá cuando la barquita "},
        { texto: "se haya hundido en la urea de los tiempos "},
        { texto: "y todas las ratas hayan aprendido a nadar,"},
        { texto: "seguirá, seguirá, seguirá, ¡cívico foxterrier "},
        { texto: "que con voracidad humillas y no humillas más por no atravesar el suelo!, "},
        { texto: "el orgullo como tema de conversación en el ascensor."},
        { texto: "pues derrítanse los cadáveres,"},
        { texto: "como copos de nieve"},
        { texto: "en el último hervor de la metrópolis, ah, "},
        { texto: "¡esta fenomenalnoria de luz y de color y de becas del Ministerio!, "},
        { texto: "seguro que seguirá esta danza cuando los gatos domésticos devoren "},
        { texto: "a los lisiados y cuando los camiones de la basura "},
        { texto: "recojan las pancartas, "},
        { texto: "seguirán las cobras y los roedores "},
        { texto: "con descaro escupiéndose, esta loca danza seguirá"},
        { texto: "cuando tú leas esto. "},
        { texto: "os quiero tanto a todos pero pienso mataros —por viles—"},
        { texto: "sirviéndome de un berrido y un afilado "},
        { texto: "tulipán." }
    ]
]