export type IPoema = IVerso[][]

export type IVerso = {
    texto: string,
    align?: 'left' | 'right' | 'center',
    hasFootNote?: boolean
}

export const poema: IPoema = [
    [
        { texto: 'Con abundante agua me quito los bostezos de la cara,' },
        { texto: 'saludo el día con un limpio pensamiento: ojalá ' },
        { texto: 'cada vez que musitara yo ' },
        { texto: '—con rabia, como mastican avena los culturistas— ' },
        { texto: 'dos o tres mecagoendioses, mis sílabas fueran un crucial y doloroso' },
        { texto: 'golpe de luz, ¡ojalá un golpe de luz!, vergüenza agarrada a un espejo. ' },
        { texto: 'mecagoendioses anagnórisis, nada queda para el poeta ' },
        { texto: 'salvo el mecagoendiós o si acaso tocar el piano. ' },
        { texto: '¡mueran la pudibundez y la melindre!' },
        { texto: 'os quiero tanto a todos pero pienso mataros ' },
        { texto: 'para corregir esta deriva, este exceso de civilización' },
    ],
    [
        { texto: "¡incívico quebrantahuesos que al cuadrúpedo derrengas!,"},
        { texto: "¿qué será desayunar la negrura de tus ojos hundidos?"},
        { texto: "¡pataplaf!", align: "right" },
        { texto: "excepcional carajillo mañanero, "},
        { texto: "peligroso y purificador, ay,"},
        { texto: "¡cívico castor que la presa construyes!, pronto desbordará la mierda "},
        { texto: "que ha de llevarnos a todos:"},
        { texto: "tu mamá te quiere y para ti ahorró muchas pesetas;"},
        { texto: "tu tía te quiere y para ti trajo un sobre con perras;"},
        { texto: "tu hermana está triste, no tiene nada que ofrecer,"},
        { texto: "la muy puta,"},
        { texto: "¿en qué lo habrá gastado?, mecagoendiós."},
        { texto: "os quiero tanto a todos pero pienso mataros "},
        { texto: "por haberme apartado de mi sueño: "},
        { texto: "ser Carlos Slim."}
    ],
    [
        { texto: "salgo desayunado de mi feliz guarida" },
        { texto: "cuando alguien, al grito de " },
        { texto: "¡algo va!", align: "right" },
        { texto: "vacía sobre mí un cubo," },
        { texto: "me empapa de la-condescendencia-del-tullido," },
        { texto: "y luego oigo con las orejitas: " },
        { texto: "«este es el resumen perfecto de tu estancia en la Tierra " },
        { texto: "desde que acudías religiosamente a tu centro de enseñanza primaria». " },
        { texto: "me lo dice un zorrito de fábula que por ahí apareció. " },
        { texto: "«te llamaré Cólera-del-Pelida», le digo." },
        { texto: "el zorrito entra al corral del hombre del cubo," },
        { texto: "destripa sin miramientos a sus gallinas ponedoras," },
        { texto: "orina sobre su título de Bachillerato. " },
        { texto: "«Cólera-del-Pelida», le digo," },
        { texto: "«no eres el fuego de los justos, pero buscas dignidad y gloria:" },
        { texto: "deseo con todo el pecho que la encuentres»," },
        { texto: "«grf, grf», contesta él.", align: 'right' },
        { texto: "aquí a la intemperie es donde suceden las cosas," },
        { texto: "donde somos testigos," },
        { texto: "conocemos la extrema pureza de los momentos;" },
        { texto: "la paz no es gregaria ni tonta aquí" },
        { texto: "no se ha inventado la paz; en fin:" },
        { texto: "qué no ha de ser regalado a quien con esta disposición camina; mecagoendiós" },
        { texto: "os quiero mucho a todos pero pienso mataros " },
        { texto: "por haberme privado de una maldad sofisticada y cierta," },
        { texto: "por haberme regalado en cambio una legión de lerdos y un zorro pequeño." },
    ],    
    [
        { texto: "acompáñame ahora a la Iglesia, Cólera-del-Pelida," },
        { texto: "la que esforzadamente levantaron nuestros papás y nuestras mamás; " },
        { texto: "por sus pasillos hay siempre una fiesta" },
        { texto: "donde se celebra el consumo de oxígeno," },
        { texto: "la correcta postura al sentarse," },
        { texto: "todo eso. la Iglesia provee a muchos" },
        { texto: "de incontables litros de condescendencia-del-tullido," },
        { texto: "te la van a echar" },
        { texto: "en el café" },
        { texto: "cuidadito." }
    ],
    [
        { texto: "mi mamá quiere que un párroco me enseñe el Trivio, el Cuadrivio" },
        { texto: "el Nosequé, el Sisemenos, así me lo ha hecho prometer." },
        { texto: "de camino a la Capilla está la gente, celebrando. " },
        { texto: "y aquel que no celebra atronadoramente no es más que un fantasma huesudo," },
        { texto: "mecagoendiós, y apenas se atreve a mirarme, ¡zorrito" },
        { texto: "al que llamo Cólera-del-Pelida! tú eres mi único amigo," },
        { texto: "la exuberancia tuya procedimental y onomástica;" },
        { texto: "tú, zorrito fabuloso," },
        { texto: "proporcionarás a los jóvenes satisfacción estética" },
        { texto: "y desafíos intelectuales" },
        { texto: "cuando yo ya no esté," },
        { texto: "«grf, grf»", align: 'right' },
        { texto: "pero el párroco en su Capilla" },
        { texto: "repite las palabras ¡tantas atropelladas veces!" },
        { texto: "son ya las frases camiones llenos de puercos, leves puercos y sucios" },
        { texto: "adelantándose unos a otros " },
        { texto: "—pero hemos prometido que vendríamos," },
        { texto: "Cólera-del-Pelida, a escucharlos a todos," },
        { texto: "todo eso que tienen que decir; después nos señalará el párroco" },
        { texto: "con su dedo de plástico", hasFootNote: true },
        { texto: "y nosotros, modulando el caudal de nuestra prosa," },
        { texto: "nos sumaremos" },
        { texto: "a la moderación general" },
        { texto: "con un comentario compendioso, nada más que " },
        { texto: "«no sé qué texto me recuerda a no sé qué película»—," },
        { texto: "en seguida estaremos fuera, te lo prometo," },
        { texto: "los quiero tanto a todos pero pienso matarlos " },
        { texto: "como quien saca de su miseria a un roedor moribundo, envenenado," },
        { texto: "que no supo distinguir entre cereal y detergente." },
    ],
    [
        { texto: "volvamos ahora a las calles calientes,  Cólera-del-Pelida" },
        { texto: "que mueves como péndulo la lengua," },
        { texto: "mazorca de maíz avinagrada, hinchada y amarilla de rabia," },
        { texto: "volvamos a las calles puesto que un rumor crece " },
        { texto: "por los pasillos agitados de la Iglesia; " },
        { texto: "no se anuncia sino el Armagedón," },
        { texto: "que se manifiesta como una singular configuración del cielo:" },
        { texto: "las nubes representan el rostro de Osama Bin Laden," },
        { texto: "el color azul nitrógeno se troca en rojo terrorista" },
        { texto: "y _pos nain ileven_." },
        { texto: "hay llanto y jaleo —porque una gran manifestación " },
        { texto: "(donde vehementemente se exigía la no existencia del Rey de España)" },
        { texto: "ha quedado atrapada en el apocalíptico impasse—." },
        { texto: "son atraídos hasta el lugar los guardianes del orden," },
        { texto: "cuya labor apreciamos pero a quienes, mecagoendiós," },
        { texto: "querríamos matar en defensa propia como hacen siempre las mujeres " },
        { texto: "que viven con el enemigo en las películas de sobremesa." },
        { texto: "¡cívico policía que la farlopa frecuentas!," },
        { texto: "no dejes que aterricen todos los hematomas" },
        { texto: "sobre las asustadizas faces," },
        { texto: "zas, zas, ahórrate alguno más; " },
        { texto: "(aún más cobarde" },
        { texto: "el tumefacto ciudadano te lo agradecerá" },
        { texto: "y nunca entre las funcionarias vértebras " },
        { texto: "habrá de situar" },
        { texto: "el debido y digno cuchillo)" },
        { texto: "«grf, grf», asiente Cólera-del-Pelida;" },
        { texto: "los guardianes se retiran " },
        { texto: "después de entregar en mano cuatrocientas hostias" },
        { texto: "y sólo al descubrirse que el Apocalipsis no era" },
        { texto: "sino la más genial campaña publicitaria de tu compañía telefónica," },
        { texto: "que saldábase con cuatro muertos y una revenue" },
        { texto: "de siete millones de dólares." },
        { texto: "nos acercamos después a una tienda," },
        { texto: "flaqueando ante tamaña " },
        { texto: "demostración de poderío, allí cambio mis monedas por un teléfono. " },
        { texto: "y aunque al poco de alejarnos siento vergüenza," },
        { texto: "«el teléfono», le digo a Cólera-del-Pelida, «es mejor que lo conserve.»" },
        { texto: "mi zorrito de fábula sólo acierta a dejar caer el rabo" },
        { texto: "en señal de decepción, y yo lloro:" },
        { texto: "apreciaba tanto mi vida pero me voy a matar" },
        { texto: "por no haber sabido captar la trascendencia de las cosas importantes," },
        { texto: "a diferencia de Everett Ruess —que se perdió en el desierto y se murió " },
        { texto: "acompañado de dos burros— o el tonto de McCandless," },
        { texto: "que dejó de comer durante demasiado tiempo" },
        { texto: "estando acampado en la salvaje Alaska." },
    ],
    [
        { texto: "al salir de la tienda de telefonía" },
        { texto: "un Policía nos golpea, Nacional, aprovechando la resaca" },
        { texto: "de las horas anteriores y emocionantes;" },
        { texto: "en nada me ayuda el zorrito," },
        { texto: "aún decepcionado," },
        { texto: "y su silencio al encajar los golpes de porra extensible" },
        { texto: "me hace verter una dorada lágrima." },
        { texto: "una vez reducidos, el guardián del nos encierra en una jaula" },
        { texto: "pequeña de hormigón, dejándonos un bacín para los orines" },
        { texto: "y una revista de peluquería." },
        { texto: "en la penumbra de nuestro confinamiento," },
        { texto: "el todavía contrariado Cólera-del-Pelida observa detenidamente" },
        { texto: "una esquina" },
        { texto: "enfrentándome con la espalda; yo intento excusarme:" },
        { texto: "«querido zorrito, ya nunca duermo más de dos horas" },
        { texto: "y en grandes cantidades bebo el vino, tengo un hijo secreto," },
        { texto: "a quien impuse mi nombre " },
        { texto: "y a quien impondré poco a poco" },
        { texto: "todos mis temores y traumas. " },
        { texto: "me acecha la muerte, aunque finjo ignorarla… he sucumbido " },
        { texto: "a la última tecnología móvil, pues" },
        { texto: "lacerado por la soledad aprieto las frustradas mandíbulas" },
        { texto: "—cada noche hasta la madrugada, mecagoendiós—" },
        { texto: "y con los ojos amoratados vago por las calles del alba" },
        { texto: "sin encontrar más comprensión que la que en ti he hallado," },
        { texto: "por todo esto te pido: " },
        { texto: "¡incívico zorrito que sobre los esclavos defecas!," },
        { texto: "no me retires tu favor»;" },
    ],
    [
        { texto: "«grf, grf», contesta él" },
        { texto: "con una sonrisa de piedad. ¡vuelve así mi fuerza!" },
        { texto: "y cierro los ojos jubiloso;" },
        { texto: "¡hormigón pálido, a ningún espíritu vigoroso" },
        { texto: "has de contener —pienso— en contra de sus juveniles deseos!" },
        { texto: "¡con el perdón del zorrito," },
        { texto: "qué no hare yo, mare," },
        { texto: "con su perdón volare," },
        { texto: "volaré el hormigón!" },
        { texto: "ideo explosiones para escapar" },
        { texto: "con los ojos y los puños cerrados." },
        { texto: "pero al despegar de nuevo los párpados encuentro el túnel" },
        { texto: "que royendo" },
        { texto: "y arañando" },
        { texto: "Cólera-del-Pelida ha abierto en nuestra jaula." },
        { texto: "¡poderoso tren inferior, cuartos traseros! gateamos y huimos" },
        { texto: "como locomotoras de luz. hoy —pienso—" },
        { texto: "seremos mejores que nadie," },
        { texto: "dioses indecisos y urgentes;" },
        { texto: "daremos a los medianos herramientas" },
        { texto: "de hierro soñador," },
        { texto: "el regalo envenenado:" },
        { texto: "la responsabilidad de ser excepcionales. nos odiarán" },
        { texto: "por unanimidad; mecagoendiós," },
        { texto: "os quiero tanto a todos pero pienso mataros" },
        { texto: "para cambiaros por muchachos peleones y divertidos," },
        { texto: "todo esto en cuanto salgamos del túnel, oscuro túnel y por lo tanto" },
        { texto: "nutricio para el pensamiento." }
    ],
    [
        { texto: "viajando por el túnel denso" },
        { texto: "mi mamífero amigo se vuelve" },
        { texto: "y me pregunta: " },
        { texto: "«¿grf, grf?»,", align: 'right' },
        { texto: "le digo «no sé yo " },
        { texto: "si lo que abunda en las esferas del poder es un batracio aliento " },
        { texto: "total y expansivo que se enseñorea," },
        { texto: "si son negras las falanges" },
        { texto: "que accionan palancas gigantescas, Cólera-del-Pelida, o somos idiotas " },
        { texto: "nada más" },
        { texto: "yo creo que somos idiotas nada más" },
        { texto: "al ser peores» eso le contesto. " },
        { texto: "sólo por amor me alegra constatar " },
        { texto: "que a mi zorrito nunca lo hiere el cansancio alevoso, " },
        { texto: "que a mi zorrito no se le cansan las patas," },
        { texto: "pues mejor para él. " },
        { texto: "ni siquiera la gente como nosotros tiene ya sitio al que regresar, " },
        { texto: "(la gente como nosotros, acomodada, " },
        { texto: "fuera de todo peligro ¿? ¿? ¿?)" },
        { texto: "no hay sitio donde caer, ni siquiera una esterilla de fitness " },
        { texto: "a la que prestar nuestros huesos cuando amanece y ya " },
        { texto: "se abren como flores las manos de la flaqueza," },
        { texto: "los amoratados ojos insomnes, " },
        { texto: "la tiesa mandíbula. recuerda esto: " },
        { texto: "dice Pitágoras en su verso más enojoso “honrarás" },
        { texto: "a tu padre y a tu madre” (como si fueran ídolos tallados en marfil, " },
        { texto: "como si no pudieran con crueldad decepcionarnos). " },
        { texto: "no habrá hogar sin hatajo de expiaciones gratuitas y arbitrarias." },
        { texto: "recorramos, Cólera-del-Pelida, este diseñado asco" },
        { texto: "como un tren las vías, hasta que se nos hinche la magnífica cabeza" },
        { texto: "y podamos bramar en el vagón: " },
        { texto: "“os quiero mucho pero pienso mataros " },
        { texto: "por haber claudicado al unísono (dejándome a solas con un zorrito), " },
        { texto: "por respirar acompasadamente”." },
    ],
    [
        { texto: "allí al final se ve la oscuridad del ocaso,"},
        { texto: "zorrito mío, ganándose la luz del entusiasmo nuestro."},
        { texto: "se acaba el túnel, y deyectados al mundo de nuevo "},
        { texto: "esquivamos los chorritos de condescendencia-del-tullido "},
        { texto: "y escupimos a la menor ocasión un poco de bilis, "},
        { texto: "¡casi se le van a uno las ganas de continuar!, "},
        { texto: "«grf, grf»,", align: 'right' },
        { texto: "parece todo una loca danza de cobras y roedores "},
        { texto: "que seguirá para siempre, "},
        { texto: "cuando yo me haya muerto "},
        { texto: "dejando sin respuesta poderosas cuestiones, "},
        { texto: "cuando las señoras heladas reivindiquen la compostura "},
        { texto: "levitando con ayuda de una soga, "},
        { texto: "seguirá cuando nos hayan golpeado a todos "},
        { texto: "al menos una vez —crujirán las caderas de nuestras madres"},
        { texto: "y quién sabe qué mandíbulas—, seguirá cuando la barquita "},
        { texto: "se haya hundido en la urea de los tiempos "},
        { texto: "y todas las ratas hayan aprendido a nadar,"},
        { texto: "seguirá, seguirá, seguirá, ¡cívico foxterrier "},
        { texto: "que con voracidad humillas y no humillas más por no atravesar el suelo!, "},
        { texto: "el orgullo como tema de conversación en el ascensor."},
        { texto: "pues derrítanse los cadáveres,"},
        { texto: "como copos de nieve"},
        { texto: "en el último hervor de la metrópolis, ah, "},
        { texto: "¡esta fenomenalnoria de luz y de color y de becas del Ministerio!, "},
        { texto: "seguro que seguirá esta danza cuando los gatos domésticos devoren "},
        { texto: "a los lisiados y cuando los camiones de la basura" },
        { texto: "recojan las pancartas, "},
        { texto: "seguirán las cobras y los roedores "},
        { texto: "con descaro escupiéndose, esta loca danza seguirá"},
        { texto: "cuando tú leas esto. "},
        { texto: "os quiero tanto a todos pero pienso mataros —por viles—"},
        { texto: "sirviéndome de un berrido y un afilado "},
        { texto: "tulipán." }
    ]
]